apiVersion: batch/v1

kind: CronJob

metadata:

  name: baywa

spec:

  schedule: "0 5 */15 * *"

  jobTemplate:

    spec:

      backoffLimit: 1
      template:

        spec:

          containers:

          - name: baywattest

            image: vishblip93/baywasrv:latest

            imagePullPolicy: IfNotPresent

            command:

            - /bin/sh

            - -c

            - python /app/app.py

          restartPolicy: OnFailure
